// Shared shape for a project's tweet kit: the posts written for X to promote one series round.
// Kits live in projects/<name>/tweets.ts and are never deployed; `npm run kit <name>` renders
// projects/<name>/tweet-kit.html with copy buttons and character counts.

export interface Tweet {
  /** Shown next to the tweet, e.g. "teaser (morning)" or "reply 2". */
  label: string
  text: string
}

export interface KitSection {
  title: string
  note?: string
  /** Adds a "copy whole thread" button. */
  thread?: boolean
  tweets: Tweet[]
}

export interface TweetKit {
  /** Folder name under projects/. */
  project: string
  title: string
  /** Public URL the campaign points at. */
  hub: string
  playbook: string[]
  schedule: { when: string; what: string; notes: string }[]
  sections: KitSection[]
}

export const TWEET_LIMIT = 280
const URL_PATTERN = /https?:\/\/\S+/g
/** X counts every link as 23 characters, whatever its real length. */
const X_LINK_LENGTH = 23

/** Length of a tweet the way X counts it: code points, with every URL counted as 23. */
export function tweetLength(text: string): number {
  return [...text.replace(URL_PATTERN, 'x'.repeat(X_LINK_LENGTH))].length
}

export function allTweets(kit: TweetKit): (Tweet & { section: string })[] {
  return kit.sections.flatMap((section) =>
    section.tweets.map((tweet) => ({ ...tweet, section: section.title })),
  )
}

export function linksIn(text: string): string[] {
  return text.match(URL_PATTERN) ?? []
}

/** Builds threads from plain strings: the first is the post, the rest are replies. */
export function thread(texts: string[]): Tweet[] {
  return texts.map((text, index) => ({ label: index === 0 ? 'first post' : `reply ${index}`, text }))
}

const escapeHtml = (text: string) =>
  text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

function renderTweet(tweet: Tweet): string {
  let length = tweetLength(tweet.text)
  let intent = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweet.text)}`
  return `<div class="tw"><div class="body">${escapeHtml(tweet.text)}</div><div class="meta"><span class="${length > TWEET_LIMIT ? 'over' : 'ok'}">${length}/${TWEET_LIMIT}</span><span class="lbl">${escapeHtml(tweet.label)}</span><button data-t="${encodeURIComponent(tweet.text)}">Copy</button><a target="_blank" rel="noopener" href="${intent}">Open in X</a></div></div>`
}

function renderSection(section: KitSection): string {
  let copyAll = section.thread
    ? `<button class="all" data-t="${encodeURIComponent(section.tweets.map((t) => t.text).join('\n\n---\n\n'))}">Copy whole thread</button>`
    : ''
  let note = section.note ? `<p>${escapeHtml(section.note)}</p>` : ''
  return `<section><h2>${escapeHtml(section.title)}</h2>${note}${copyAll}${section.tweets.map(renderTweet).join('')}</section>`
}

/** A standalone HTML page for working through a kit: copy buttons, counts, intent links. */
export function renderKit(kit: TweetKit): string {
  let schedule = kit.schedule
    .map((row) => `<tr><td>${escapeHtml(row.when)}</td><td>${escapeHtml(row.what)}</td><td>${escapeHtml(row.notes)}</td></tr>`)
    .join('')
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex">
<title>${escapeHtml(kit.title)}: tweet kit</title>
<!-- Generated by \`npm run kit ${kit.project}\` from projects/${kit.project}/tweets.ts. Do not edit by hand. -->
<style>
:root{--bg:#14171B;--card:#1B1F25;--ink:#E9E7E2;--muted:#9AA3AC;--accent:#F0975A;--line:#2A2F36}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
main{max-width:760px;margin:0 auto;padding:40px 20px 100px}
a{color:var(--accent)}
h1{font-family:ui-monospace,Menlo,monospace;letter-spacing:-.03em;margin:0 0 6px}
h2{font-family:ui-monospace,Menlo,monospace;font-size:18px;margin:44px 0 10px;padding-top:24px;border-top:1px solid var(--line)}
p,li{color:var(--muted)}
table{width:100%;border-collapse:collapse;font-size:14px}td,th{border-bottom:1px solid var(--line);padding:8px;text-align:left;vertical-align:top}th{color:var(--muted)}
.tw{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:14px 16px;margin:10px 0}
.body{white-space:pre-wrap}
.meta{display:flex;flex-wrap:wrap;gap:12px;align-items:center;margin-top:10px;font-size:12px;font-family:ui-monospace,Menlo,monospace}
.ok{color:#5BD08A}.over{color:#F87171;font-weight:700}.lbl{color:var(--muted)}
button,.meta a{background:none;border:1px solid var(--accent);color:var(--accent);border-radius:7px;padding:3px 9px;cursor:pointer;font:inherit;text-decoration:none}
button.all{margin:4px 0 6px;font-family:ui-monospace,Menlo,monospace;font-size:12px}
.k{color:var(--accent);font-family:ui-monospace,Menlo,monospace;font-size:12px;text-transform:uppercase;letter-spacing:.1em}
</style>
</head>
<body><main>
<p class="k">tweet kit · not deployed</p>
<h1>${escapeHtml(kit.title)}</h1>
<p>Counts treat every link as 23 characters, as X does. Campaign page: <a href="${kit.hub}">${kit.hub}</a></p>
<h2>Playbook</h2>
<ul>${kit.playbook.map((line) => `<li>${escapeHtml(line)}</li>`).join('')}</ul>
<h2>Schedule</h2>
<table><tr><th>When</th><th>Post</th><th>Notes</th></tr>${schedule}</table>
${kit.sections.map(renderSection).join('\n')}
</main>
<script>
document.addEventListener('click', async (event) => {
  let button = event.target.closest('button[data-t]')
  if (!button) return
  await navigator.clipboard.writeText(decodeURIComponent(button.dataset.t))
  let label = button.textContent
  button.textContent = 'Copied ✓'
  setTimeout(() => { button.textContent = label }, 1200)
})
</script>
</body>
</html>
`
}
